name: Deploy Red Legion Website

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy PHP Website to GCP

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Deploy with Ansible
      run: |
        cd ansible
        ansible-playbook -i inventory.ini deploy.yml \
          -e "db_host=${{ secrets.DB_HOST }}" \
          -e "db_port=${{ secrets.DB_PORT }}" \
          -e "db_name=${{ secrets.DB_NAME }}" \
          -e "db_user=${{ secrets.DB_USER }}" \
          -e "db_pass=${{ secrets.DB_PASS }}" \
          --ssh-common-args='-o StrictHostKeyChecking=no'

    - name: Verify deployment
      run: |
        echo "PHP Website deployment completed!"
        echo "Main site: http://dev.redlegion.gg/"
        echo "Management portal: http://dev.redlegion.gg/management/"