name: Deploy Red Legion Website

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy PHP Website to GCP

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Test SSH connectivity
      run: |
        echo "Testing SSH connection to web server..."
        gcloud compute ssh ubuntu@arccorp-web-server --zone us-central1-a --command "echo 'SSH connection successful!'" --ssh-flag="-o ConnectTimeout=10"

    - name: Deploy website with simple script
      run: |
        echo "Copying deployment script to server..."
        gcloud compute scp deploy.sh ubuntu@arccorp-web-server:/tmp/ --zone us-central1-a

        echo "Running lightweight deployment..."
        gcloud compute ssh ubuntu@arccorp-web-server --zone us-central1-a --command "
          chmod +x /tmp/deploy.sh
          /tmp/deploy.sh
          rm -f /tmp/deploy.sh
        "

        echo "Copying website files to server..."
        gcloud compute scp --recurse public_html ubuntu@arccorp-web-server:/tmp/ --zone us-central1-a
        gcloud compute scp --recurse app ubuntu@arccorp-web-server:/tmp/ --zone us-central1-a
        gcloud compute scp composer.json ubuntu@arccorp-web-server:/tmp/ --zone us-central1-a

        echo "Creating production .env file..."
        echo "APP_ENV=prod" > /tmp/.env
        echo "APP_NAME=The Red Legion Public Website" >> /tmp/.env
        echo "APP_TZ=UTC" >> /tmp/.env
        echo "" >> /tmp/.env
        echo "# Discord OAuth Configuration" >> /tmp/.env
        echo "DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }}" >> /tmp/.env
        echo "DISCORD_CLIENT_SECRET=${{ secrets.DISCORD_CLIENT_SECRET }}" >> /tmp/.env
        echo "DISCORD_REDIRECT_URI=${{ secrets.DISCORD_REDIRECT_URI }}" >> /tmp/.env
        echo "DISCORD_BOT_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> /tmp/.env
        echo "" >> /tmp/.env
        echo "# Red Legion Discord Server ID" >> /tmp/.env
        echo "RED_LEGION_GUILD_ID=814699481912049704" >> /tmp/.env

        echo "Copying .env file to server..."
        gcloud compute scp /tmp/.env ubuntu@arccorp-web-server:/tmp/ --zone us-central1-a

        echo "Installing website files..."
        gcloud compute ssh ubuntu@arccorp-web-server --zone us-central1-a --command "
          sudo cp -r /tmp/public_html/* /opt/red-legion-website/public_html/
          sudo cp -r /tmp/app /opt/red-legion-website/
          sudo cp /tmp/composer.json /opt/red-legion-website/
          sudo mv /tmp/.env /opt/red-legion-website/.env

          sudo chown -R www-data:www-data /opt/red-legion-website
          sudo chmod 600 /opt/red-legion-website/.env

          # Install composer dependencies
          cd /opt/red-legion-website
          sudo -u www-data composer install --no-dev --optimize-autoloader

          # Clean up temp files
          rm -rf /tmp/public_html /tmp/app /tmp/composer.json
        "

    - name: Verify deployment
      run: |
        echo "Verifying website is accessible..."
        gcloud compute ssh ubuntu@arccorp-web-server --zone us-central1-a --command "
          echo 'Checking services...'
          systemctl is-active nginx || echo 'Nginx not running'
          systemctl is-active php8.1-fpm || echo 'PHP-FPM not running'
          systemctl is-active mysql || echo 'MySQL not running'

          echo 'Testing web server response...'
          curl -I http://localhost/ || echo 'Website not responding'
        "

        echo "🎉 Deployment completed!"
        echo "Website: http://dev.redlegion.gg/"
        echo "phpMyAdmin: http://dev.redlegion.gg/pma"