name: Deploy Red Legion Website

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy PHP Website to GCP

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Install Ansible and configure gcloud SSH
      run: |
        python -m pip install --upgrade pip
        pip install ansible

        # Configure gcloud SSH wrapper for Ansible
        mkdir -p ~/.ssh
        cat > ~/.ssh/gcloud_ssh_wrapper.sh << 'EOF'
#!/bin/bash
exec gcloud compute ssh --zone=us-central1-a "$@"
EOF
        chmod +x ~/.ssh/gcloud_ssh_wrapper.sh

    - name: Deploy with Ansible using gcloud connectivity
      run: |
        cd ansible

        # Create dynamic inventory with gcloud SSH proxy
        cat > inventory-gcloud.ini << 'EOF'
[web_servers]
arccorp-web-server ansible_host=ubuntu@arccorp-web-server

[web_servers:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_executable=~/.ssh/gcloud_ssh_wrapper.sh
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_host_key_checking=False
EOF

        # Run Ansible playbook with gcloud SSH proxy
        export ANSIBLE_HOST_KEY_CHECKING=False
        ansible-playbook -i inventory-gcloud.ini deploy.yml \
          -e "db_host=localhost" \
          -e "db_port=3306" \
          -e "db_name=red_legion_website" \
          -e "db_user=website_user" \
          -e "db_pass=temp_password_to_be_changed" \
          -v

    - name: Verify deployment
      run: |
        echo "PHP Website deployment completed!"
        echo "Main site: http://dev.redlegion.gg/"
        echo "Management portal: http://dev.redlegion.gg/management/"