name: Deploy Red Legion Website

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy PHP Website to GCP

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy website files
      run: |
        # Create deployment directory on server first
        gcloud compute ssh ubuntu@arccorp-web-server --zone us-central1-a --command "
          sudo mkdir -p /tmp/red-legion-website-deploy
          sudo chown ubuntu:ubuntu /tmp/red-legion-website-deploy
        "

        # Copy website files to server
        gcloud compute scp --recurse . ubuntu@arccorp-web-server:/tmp/red-legion-website-deploy/ --zone us-central1-a

        # Deploy and configure on server
        gcloud compute ssh ubuntu@arccorp-web-server --zone us-central1-a --command "
          # Create website directory
          sudo mkdir -p /opt/red-legion-website

          # Backup existing files if they exist
          if [ -d '/opt/red-legion-website/public_html' ]; then
            sudo rm -rf /opt/red-legion-website/backup || true
            sudo mkdir -p /opt/red-legion-website/backup
            sudo cp -r /opt/red-legion-website/* /opt/red-legion-website/backup/ 2>/dev/null || true
          fi

          # Copy new files
          sudo rm -rf /opt/red-legion-website/app /opt/red-legion-website/public_html || true
          sudo cp -r /tmp/red-legion-website-deploy/app /opt/red-legion-website/
          sudo cp -r /tmp/red-legion-website-deploy/public_html /opt/red-legion-website/
          sudo chown -R www-data:www-data /opt/red-legion-website

          # Install PHP and MySQL if not already installed
          sudo apt update
          # Add PHP repository for newer versions
          sudo apt install -y software-properties-common
          sudo add-apt-repository -y ppa:ondrej/php
          sudo apt update
          sudo apt install -y php8.1 php8.1-fpm php8.1-mysql php8.1-curl php8.1-gd php8.1-xml php8.1-mbstring php8.1-zip mysql-server composer

          # Configure PHP-FPM
          sudo systemctl enable php8.1-fpm
          sudo systemctl start php8.1-fpm

          # Install Composer dependencies if composer.json exists
          if [ -f '/opt/red-legion-website/composer.json' ]; then
            cd /opt/red-legion-website
            sudo -u www-data composer install --no-dev --optimize-autoloader
          fi

          # Create basic .env file
          sudo tee /opt/red-legion-website/.env > /dev/null <<EOF
        APP_ENV=production
        APP_NAME='Red Legion'
        DB_HOST='${{ secrets.DB_HOST }}'
        DB_PORT='${{ secrets.DB_PORT }}'
        DB_NAME='${{ secrets.DB_NAME }}'
        DB_USER='${{ secrets.DB_USER }}'
        DB_PASS='${{ secrets.DB_PASS }}'
        EOF

          sudo chown www-data:www-data /opt/red-legion-website/.env
          sudo chmod 640 /opt/red-legion-website/.env

          # Configure Nginx for both sites
          sudo tee /etc/nginx/sites-available/red-legion > /dev/null <<'NGINX_EOF'
        # Main website (PHP)
        server {
            listen 80 default_server;
            listen [::]:80 default_server;
            server_name dev.redlegion.gg;
            root /opt/red-legion-website/public_html;
            index index.php index.html;

            # Security headers
            add_header X-Frame-Options DENY;
            add_header X-Content-Type-Options nosniff;
            add_header X-XSS-Protection \"1; mode=block\";

            # Main site PHP processing
            location / {
                try_files \$uri \$uri/ /index.php?\$query_string;
            }

            location ~ \\.php\$ {
                fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
                include fastcgi_params;
            }

            # Management portal (reverse proxy to FastAPI)
            location /management/ {
                proxy_pass http://127.0.0.1:8000/;
                proxy_http_version 1.1;
                proxy_set_header Host \$host;
                proxy_set_header X-Real-IP \$remote_addr;
                proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto \$scheme;
                proxy_read_timeout 300;
                proxy_connect_timeout 300;
                proxy_send_timeout 300;
            }

            # Management portal static files
            location /management/static/ {
                alias /opt/red-legion-management-portal/static/;
                expires 1y;
                add_header Cache-Control \"public, immutable\";
            }

            location /management/assets/ {
                alias /opt/red-legion-management-portal/frontend/dist/assets/;
                expires 1y;
                add_header Cache-Control \"public, immutable\";
            }

            # Block common attack patterns
            location ~* \\.(env|git|svn)\$ {
                deny all;
                return 404;
            }
        }
        NGINX_EOF

          # Enable the site (remove any existing conflicting configs)
          sudo rm -f /etc/nginx/sites-enabled/default
          sudo rm -f /etc/nginx/sites-enabled/red-legion
          sudo ln -sf /etc/nginx/sites-available/red-legion /etc/nginx/sites-enabled/

          # Test and reload Nginx
          sudo nginx -t
          sudo systemctl reload nginx

          # Clean up temp files
          sudo rm -rf /tmp/red-legion-website-deploy
        "

    - name: Verify deployment
      run: |
        echo "PHP Website deployment completed!"
        echo "Main site: http://dev.redlegion.gg/"
        echo "Management portal: http://dev.redlegion.gg/management/"