name: Deploy Red Legion Website

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy PHP Website to GCP

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Setup Python and Ansible
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Ansible
      run: |
        pip install ansible
        pip install google-auth

    - name: Test SSH connectivity
      run: |
        echo "Testing SSH connection to web server..."
        gcloud compute ssh ubuntu@arccorp-web-server --zone us-central1-a --command "echo 'SSH connection successful!'" --ssh-flag="-o ConnectTimeout=10"

    - name: Create gcloud SSH wrapper
      run: |
        cat > gcloud-ssh-wrapper.sh << 'EOF'
        #!/bin/bash
        gcloud compute ssh ubuntu@arccorp-web-server --zone us-central1-a --ssh-flag="-o StrictHostKeyChecking=no" -- "$@"
        EOF
        chmod +x gcloud-ssh-wrapper.sh

    - name: Deploy website with Ansible
      run: |
        export ANSIBLE_SSH_EXECUTABLE=$(pwd)/gcloud-ssh-wrapper.sh
        cd ansible
        ansible-playbook -i inventory.ini deploy.yml \
          -e db_name=red_legion_website \
          -e db_user=website_user \
          -e db_pass=temp_password_to_be_changed \
          -e discord_client_id="${{ secrets.DISCORD_CLIENT_ID }}" \
          -e discord_client_secret="${{ secrets.DISCORD_CLIENT_SECRET }}" \
          -e discord_redirect_uri="${{ secrets.DISCORD_REDIRECT_URI }}" \
          -e discord_bot_token="${{ secrets.DISCORD_TOKEN }}" \
          -e pma_password=pmapassword_change_me \
          -e admin_password=RedLegion2024! \
          --ssh-extra-args="-o StrictHostKeyChecking=no"

    - name: Verify deployment
      run: |
        echo "Verifying website is accessible..."
        gcloud compute ssh ubuntu@arccorp-web-server --zone us-central1-a --command "
          echo 'Checking services...'
          systemctl is-active nginx || echo 'Nginx not running'
          systemctl is-active php8.1-fpm || echo 'PHP-FPM not running'
          systemctl is-active mysql || echo 'MySQL not running'

          echo 'Testing web server response...'
          curl -I http://localhost/ || echo 'Website not responding'
        "

        echo "🎉 Deployment completed!"
        echo "Website: http://dev.redlegion.gg/"
        echo "phpMyAdmin: http://dev.redlegion.gg/pma"